
title: "MEEC Workshop at CHI 2020"
logo: "./assets/imgs/logo1.png"
description: "Towards better methods for Momentary Emotion Elicitation and Capture."

# minimal_mistakes_skin: "contrast"
search: false

author:
  name     : "MEEC 2020 WS"
  avatar   : "./assets/imgs/logo2.png"
  bio      : "Something"
  location : "Somewhere"

footer:

kramdown:
  auto_ids: false

plugins:
  - jekyll-include-cache

remote_theme: mmistakes/minimal-mistakes

atom_feed: false

# defaults:
#   # _pages
#   - scope:
#       path: ""
#       type: pages
#     values:
#       layout: single
#       author_profile: false
